### ISSUE TITLE
Update to 0.14.0

### ISSUE THREAD

**Issue by alehatsman** [flosell/lambdacd-template#1]
Hello,

Seems like that template is a little bit outdated.

Aleh

**Comment by flosell** [comment]
Thanks for raising this! 

The template includes `lambda-ui` which is not yet compatible with `0.14.0`, that's why I haven't updated it yet. I created a PR (sroidl/lambda-ui#105) on this but I usually avoid merging them without review since I'm just the co-maintainer there. 

I'll keep this issue open and hope to have an update in a couple of days.

**Comment by flosell** [comment]
Good news: lambda-ui fixes are released and I bumped the versions in this template as well, everything should be up to date now.

**Comment by alehatsman** [comment]
cool!!!
